services:
  - type: web
    name: ob-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    runtime: python3.12  # Stable, kompatybilne z pandas 2.1.0
